TokenAuthentication/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', TemplateView.as_view(template_name='accounts/login_form.html'), name='login_form'),
                  url(r'^admin/', admin.site.urls),
                  url(r'^polls/', include('polls.urls', namespace="polls")),
                  url(r'^accounts/', include('accounts.urls', namespace="accounts")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from rest_framework.authtoken import views as rest_framework_views
from accounts.views import login_user, logout_user

urlpatterns = [
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
]

polls/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from polls.serializers import QuestionList, QuestionDetail, ChoiceDetail, UserCreate, UserDetail
from . import views

urlpatterns = [
                  # Regular Django Views
                  url(r'^$', login_required(views.index), name='index'),
                  url(r'^(?P<pk>[0-9]+)/$', login_required(views.Detail.as_view()), name='detail'),
                  url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.Results.as_view()), name='results'),
                  url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),

                  # API views
                  url(r'^api/questions/$', QuestionList.as_view(), name="api_questions"),
                  url(r'^api/questions/(?P<pk>[0-9]+)/$', QuestionDetail.as_view()),
                  url(r'^api/choices/(?P<pk>[0-9]+)/$', ChoiceDetail.as_view()),
                  url(r'^api/create_user/$', UserCreate.as_view()),
                  url(r'^api/users/(?P<pk>[0-9]+)/$', UserDetail.as_view()),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices")
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

accounts/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from rest_framework.authtoken.models import Token


def login_user(request):
    if request.user.is_authenticated() and request.COOKIES.get('token') == request.session['auth']:
        return HttpResponseRedirect(settings.LOGIN_URL)
    else:
        auth.logout(request)

    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)

    if user is not None:
        # the password verified for the user
        if user.is_active:
            token, created = Token.objects.get_or_create(user=user)
            request.session['auth'] = token.key
            auth.login(request, user)
            return redirect(settings.LOGIN_URL, request)

    return redirect(settings.LOGIN_URL, request)


def logout_user(request):
    auth.logout(request)
    return redirect(settings.LOGIN_URL, request)

polls/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView

from .models import Choice, Question


def index(request):
    template_name = 'polls/index.html'
    questions = Question.objects.all()

    context = {
        "questions": questions
    }
    return render(request, template_name, context)


class Detail(DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get(self, request, *args, **kwargs):
        question = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return render(request, self.template_name, {'question': question})


class Results(DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get(self, request, *args, **kwargs):
        question = get_object_or_404(self.model, pk=self.kwargs['pk'])

        return render(request, self.template_name, {'question': question})


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

templates/accounts/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
    <script src="{% static "jquery-2.2.4.min.js" %}"></script>
    <meta name="robots" content="NONE,NOARCHIVE">
</head>
<body>
<div style="position: absolute; left: 50%;top: 10%;">
    <div style="position: relative; left: -50%;">
        {% if request.COOKIES.token and request.user.is_authenticated %}
            <h1>YOUR TOKEN</h1>
            <h1>{{ request.COOKIES.token }}</h1>
            <input type="submit" value="Logout" id="logout"><br>
            <a href="{% url 'polls:index' %}"><input type="submit" value="Question list"></a>
            <input type="submit" value="Questions json" id="qs">
            <br>
            <img src="{% static "json.png" %}" width="125%">
        {% else %}
            <form action="{% url 'accounts:login' %}" method="post" onsubmit="false">
                <h1>LOGIN</h1>
                <span>Username:</span>
                {% csrf_token %}
                <input type='text' name='username' id='username' title="Username">
                <br>
                <br>
                <span>Password:</span>
                <input type='password' name='password' id='password' title="Password">
                <br>
                <br>
                <input type="submit" value="Login" id="login_form">
            </form>
        {% endif %}
    </div>
</div>
</body>
<script>
    $("#login_form").on("click", function (e) {
        var username = $("#username").val();
        var password = $("#password").val();

        $.post("{% url 'accounts:get_auth_token' %}", {
            "username": username,
            "password": password
        }).success(function (data) {
            var token = data["token"];
            document.cookie = 'token=' + token + ";path=/";
            $("form").submit();
        });
    });

    $("#logout").on("click", function (e) {
        document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/";
        location.href = "{% url 'accounts:logout' %}";
    });

    $("#qs").on("click", function (e) {
        var cookies = document.cookie.split(/;\s*/);
        var token = "";
        var headers = null;

        for (var i = 0; i < cookies.length; i++) {
            var c = cookies[i];
            if (c.startsWith("token")) {
                token = c.split("=")[1];
                headers = {'Authorization': 'Token ' + token};
            }
        }

        $.ajax({
            url: "{% url 'polls:api_questions' %}",
            headers: headers,

            success: function (result) {
                alert("SUCCESS! Please observe tool Network")
            },

            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert(errorThrown);
            }
        });
    });

</script>
</html>

templates/polls/base.html
{% load staticfiles %}
<html>
<head>
    <title>Angular + Django</title>
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/base.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1><a href="{% url 'polls:index' %}">Index</a></h1>
    <br>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choices.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>
{% endblock %}

templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
     <h1><a href="{% url 'login_form' %}">HOME</a></h1>
    {% if questions %}
        <ul>
            {% for question in questions %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1><a href="{% url 'polls:index' %}">Index</a></h1>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choices.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}